# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Init Database
      run: docker compose up -d postgres

    - name: Lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1
        args: controllers/ database/ models/ routes/
        
    - name: Test
      run: DB_HOST=${{secrets.DB_HOST}} DB_PORT=${{secrets.DB_PORT}} DB_USER=${{secrets.DB_USER}} DB_PASSWORD=${{secrets.DB_PASSWORD}} DB_NAME=${{secrets.DB_NAME}}  go test -v main_test.go
    
    - name: Build
      run: go build main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: main
        path: main